#municipality (municipio)
#seller (vendedor)
#document_type (tipo de documento)
#product_type (tipo de producto)
#product (producto)
#customer (cliente)
#invoice (factura)
#invoice_product (producto de factura)
#department (departamento)
#country (país)